# This file is generated by Nx.
#
# Build the docker image with `npx nx docker-build contractnix-api`.
# Tip: Modify "docker-build" options in project.json to change docker build args.
#
# Run the container with `docker run -p 3000:3000 -t contractnix-api`.
FROM docker.io/node:lts-alpine

ENV HOST=0.0.0.0
ENV PORT=3000

WORKDIR /app

RUN addgroup --system contractnix-api && \
          adduser --system -G contractnix-api contractnix-api

COPY dist/contractnix-api contractnix-api
RUN chown -R contractnix-api:contractnix-api .

# You can remove this install step if you build with `--bundle` option.
# The bundled output will include external dependencies.
# RUN npm --prefix contractnix-api --omit=dev -f install

CMD [ "node", "contractnix-api" ]
